### ISSUE TITLE
03_06_lambdas_captures.cpp capture this by copy does not compile 

### ISSUE THREAD

**Issue by wendlerc** [PeterTh/uibk_cpp#1] opened 2018-11-24 07:37 UTC
see title.

**Comment by PeterTh** [comment] 2018-11-28 16:06
Hi, I can not reproduce this issue: https://godbolt.org/z/VVQxLE
(Using C++17 compliant compilers)

**Comment by PeterTh** [comment] 2018-12-04 10:01
Closing due to lack of reproducibility/followup.

**Closed as completed by PeterTh** 2018-12-04 10:01 UTC
